apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: techmefi-hpa
  namespace: tmefi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techmefi-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale when CPU usage > 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # Scale when Memory usage > 70%