apiVersion: v1
kind: PersistentVolume
metadata:
  name: techmefi-pv
  namespace: tmefi
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/ubuntu/techmefi.com
    type: DirectoryOrCreate