apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techmefi-pvc
  namespace: tmefi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard